openapi: 3.0.0
info:
  title: OKR Express API - Check-ins
  version: 1.0.0
  description: Check-in management endpoints for OKR Express API

paths:
  /api/check-ins:
    post:
      summary: Create a new check-in for an OKR
      tags: [Check-ins]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - okrId
                - updates
              properties:
                okrId:
                  type: string
                updates:
                  type: array
                  items:
                    type: object
                    required:
                      - index
                      - newProgress
                    properties:
                      index:
                        type: number
                        minimum: 0
                      newProgress:
                        type: number
                        minimum: 0
                        maximum: 100
                comment:
                  type: string
      responses:
        '201':
          description: Check-in created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  checkIn:
                    $ref: '../common.yaml#/components/schemas/CheckIn'
        '400':
          description: Invalid key result index or progress value
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have access to this OKR
        '404':
          description: OKR not found

    get:
      summary: Get check-ins for an OKR
      tags: [Check-ins]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: okrId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of check-ins
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../common.yaml#/components/schemas/CheckIn'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have access to this OKR
        '404':
          description: OKR not found

  /api/check-ins/{checkInId}:
    get:
      summary: Get check-in details
      tags: [Check-ins]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: checkInId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Check-in details
          content:
            application/json:
              schema:
                $ref: '../common.yaml#/components/schemas/CheckIn'
        '401':
          description: Unauthorized
        '404':
          description: Check-in not found 