openapi: 3.0.0
info:
  title: OKR Express API - OKRs
  version: 1.0.0
  description: OKR management endpoints for OKR Express API

paths:
  /api/okrs:
    post:
      summary: Create a new OKR
      tags: [OKRs]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - companyId
                - keyResults
              properties:
                title:
                  type: string
                companyId:
                  type: string
                teamId:
                  type: string
                description:
                  type: string
                keyResults:
                  type: array
                  items:
                    type: object
                    required:
                      - title
                      - target
                    properties:
                      title:
                        type: string
                      description:
                        type: string
                      target:
                        type: number
                        minimum: 0
                        maximum: 100
      responses:
        '201':
          description: OKR created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  okr:
                    $ref: '../common.yaml#/components/schemas/OKR'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to create OKRs in this company/team
        '404':
          description: Company or Team not found

    get:
      summary: Get all OKRs
      tags: [OKRs]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: companyId
          schema:
            type: string
        - in: query
          name: teamId
          schema:
            type: string
      responses:
        '200':
          description: List of OKRs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../common.yaml#/components/schemas/OKR'
        '401':
          description: Unauthorized

  /api/okrs/{okrId}:
    get:
      summary: Get OKR details
      tags: [OKRs]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: okrId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OKR details
          content:
            application/json:
              schema:
                $ref: '../common.yaml#/components/schemas/OKR'
        '401':
          description: Unauthorized
        '404':
          description: OKR not found

  /api/okrs/{okrId}/key-results:
    post:
      summary: Add key result to OKR
      tags: [OKRs]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: okrId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - target
              properties:
                title:
                  type: string
                description:
                  type: string
                target:
                  type: number
                  minimum: 0
                  maximum: 100
      responses:
        '201':
          description: Key result added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  okr:
                    $ref: '../common.yaml#/components/schemas/OKR'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to modify this OKR
        '404':
          description: OKR not found

  /api/okrs/{okrId}/key-results/{krId}:
    put:
      summary: Update key result
      tags: [OKRs]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: okrId
          required: true
          schema:
            type: string
        - in: path
          name: krId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                target:
                  type: number
                  minimum: 0
                  maximum: 100
                progress:
                  type: number
                  minimum: 0
                  maximum: 100
      responses:
        '200':
          description: Key result updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  okr:
                    $ref: '../common.yaml#/components/schemas/OKR'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to modify this OKR
        '404':
          description: OKR or Key Result not found

    delete:
      summary: Delete key result
      tags: [OKRs]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: okrId
          required: true
          schema:
            type: string
        - in: path
          name: krId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Key result deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  okr:
                    $ref: '../common.yaml#/components/schemas/OKR'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to modify this OKR
        '404':
          description: OKR or Key Result not found 