openapi: 3.0.0
info:
  title: OKR Express API - Teams
  version: 1.0.0
  description: Team management endpoints for OKR Express API

paths:
  /api/teams:
    post:
      summary: Create a new team
      tags: [Teams]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - companyId
              properties:
                name:
                  type: string
                companyId:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Team created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  team:
                    $ref: '../common.yaml#/components/schemas/Team'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to create teams in this company
        '404':
          description: Company not found

    get:
      summary: Get all teams
      tags: [Teams]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../common.yaml#/components/schemas/Team'
        '401':
          description: Unauthorized

  /api/teams/{teamId}:
    get:
      summary: Get team details
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Team details
          content:
            application/json:
              schema:
                $ref: '../common.yaml#/components/schemas/Team'
        '401':
          description: Unauthorized
        '404':
          description: Team not found

  /api/teams/{teamId}/members:
    get:
      summary: Get team members
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of team members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../common.yaml#/components/schemas/User'
        '401':
          description: Unauthorized
        '404':
          description: Team not found

  /api/teams/{teamId}/users:
    post:
      summary: Add user to team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
      responses:
        '201':
          description: User added to team successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  team:
                    $ref: '../common.yaml#/components/schemas/Team'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to add members to this team
        '404':
          description: Team or User not found
        '400':
          description: User is already in this team

  /api/teams/{teamId}/users/bulk:
    post:
      summary: Add multiple users to team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userIds
              properties:
                userIds:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Users added to team successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  team:
                    $ref: '../common.yaml#/components/schemas/Team'
                  addedUsers:
                    type: array
                    items:
                      $ref: '../common.yaml#/components/schemas/User'
                  failedUsers:
                    type: array
                    items:
                      type: object
                      properties:
                        userId:
                          type: string
                        reason:
                          type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to add members to this team
        '404':
          description: Team not found

  /api/teams/{teamId}/users/{userId}:
    delete:
      summary: Remove user from team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User removed from team successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  team:
                    $ref: '../common.yaml#/components/schemas/Team'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User does not have permission to remove members from this team
        '404':
          description: Team or User not found
        '400':
          description: User is not in this team 