openapi: 3.0.0
info:
  title: Teams API
  version: 1.0.0
  description: API for managing teams and their members

paths:
  /api/teams:
    post:
      summary: Create a new team
      tags: [Teams]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - companyId
              properties:
                name:
                  type: string
                companyId:
                  type: string
      responses:
        '201':
          description: Team created successfully
        '400':
          description: Invalid request body
        '401':
          description: Unauthorized
        '404':
          description: Company not found
    get:
      summary: Get all teams
      description: Returns a list of teams for a specific company
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: companyId
          required: true
          schema:
            type: string
          description: ID of the company to get teams for
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams:
                    type: array
                    items:
                      $ref: '#/components/schemas/Team'
        '400':
          description: Bad Request - Company ID is required
        '401':
          description: Unauthorized
        '404':
          description: Company not found

  /api/teams/{teamId}:
    get:
      summary: Get team details
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Team details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '401':
          description: Unauthorized
        '404':
          description: Team not found
    delete:
      summary: Delete team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Team deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Team not found

  /api/teams/{teamId}/users:
    post:
      summary: Add user to team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
      responses:
        '201':
          description: User added to team successfully
        '400':
          description: User is already in this team
        '401':
          description: Unauthorized
        '404':
          description: Team not found or User not found

  /api/teams/{teamId}/users/{userId}:
    delete:
      summary: Remove user from team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User removed from team successfully
        '400':
          description: User is not in this team
        '401':
          description: Unauthorized
        '404':
          description: Team not found

  /api/teams/{teamId}/users/bulk:
    post:
      summary: Add multiple users to team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userIds
              properties:
                userIds:
                  type: array
                  items:
                    type: string
                  description: Array of user IDs to add
      responses:
        '201':
          description: Users added successfully
        '400':
          description: Invalid user IDs or all users already in team
        '401':
          description: Unauthorized
        '404':
          description: Team not found or some users not found

  /api/teams/{teamId}/users/bulk-remove:
    post:
      summary: Bulk remove users from team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userIds
              properties:
                userIds:
                  type: array
                  items:
                    type: string
                  description: Array of user IDs to remove from the team
      responses:
        '200':
          description: Users successfully removed from team
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  removedCount:
                    type: number
        '400':
          description: Invalid request body
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Only team creator can remove users
        '404':
          description: Team not found

  /api/teams/{teamId}/roles:
    post:
      summary: Add required role to team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - roleName
              properties:
                roleName:
                  type: string
      responses:
        '201':
          description: Role added successfully
        '400':
          description: Role is already required for this team
        '401':
          description: Unauthorized
        '404':
          description: Team not found or Role not found in company

  /api/teams/{teamId}/roles/{roleName}:
    delete:
      summary: Remove required role from team
      description: Removes a role from the list of required roles for the team. This operation does not affect team members who already have this role.
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
        - in: path
          name: roleName
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Role removed successfully from required roles
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  team:
                    $ref: '#/components/schemas/Team'
        '400':
          description: Role is not required for this team
        '401':
          description: Unauthorized
        '404':
          description: Team not found

  /api/teams/{teamId}/roles/bulk:
    post:
      summary: Add multiple required roles to team
      tags: [Teams]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - roles
              properties:
                roles:
                  type: array
                  items:
                    type: string
                  description: Array of role names to add
      responses:
        '201':
          description: Roles added successfully
        '400':
          description: Invalid roles or all roles already required
        '401':
          description: Unauthorized
        '404':
          description: Team not found or Company not found

components:
  schemas:
    Team:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        companyId:
          type: string
        createdBy:
          type: string
        members:
          type: array
          items:
            type: object
            properties:
              userId:
                type: string
        requiredRoles:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time 